apiVersion: v1
name: s3control-chart
description: A Helm chart for the ACK service controller for AWS S3 Control (S3 Control)
version: 1.0.0
appVersion: 1.0.0
home: https://github.com/aws-controllers-k8s/s3control-controller
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws-controllers-k8s/s3control-controller
maintainers:
  - name: ACK Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ack-admin
  - name: S3 Control Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/s3control-maintainer
keywords:
  - aws
  - kubernetes
  - s3control
